// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtXtEvPEwaHx-2a1B-JdAaRYhu-2jbnVA',
    appId: '1:530491005404:web:c98959cd285ac9dd795719',
    messagingSenderId: '530491005404',
    projectId: 'chatapp-980f9',
    authDomain: 'chatapp-980f9.firebaseapp.com',
    storageBucket: 'chatapp-980f9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDxqDuzu4meUY3Fa1OKufamXvI1mUXgsE',
    appId: '1:530491005404:android:86458c99edaef7af795719',
    messagingSenderId: '530491005404',
    projectId: 'chatapp-980f9',
    storageBucket: 'chatapp-980f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXgVG0w_GY6j6UETdoU-ZKzh4zGtbiv4M',
    appId: '1:530491005404:ios:b1c2db56a0810db0795719',
    messagingSenderId: '530491005404',
    projectId: 'chatapp-980f9',
    storageBucket: 'chatapp-980f9.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXgVG0w_GY6j6UETdoU-ZKzh4zGtbiv4M',
    appId: '1:530491005404:ios:8e71f3d0ce88c971795719',
    messagingSenderId: '530491005404',
    projectId: 'chatapp-980f9',
    storageBucket: 'chatapp-980f9.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
